## MySQL Configuration
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/schema_crud
#spring.datasource.username=root
#spring.datasource.password=Qaz123321
#
#spring.jpa.show-sql=true
#spring.jpa.open-in-view=false
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.format_sql=true
#spring.mvc.hiddenmethod.filter.enabled=true
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schema_crud
    username: root
    password: Qaz123321

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true